# Generated by Django 2.2.7 on 2022-03-29 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_clientcompanies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('display_name', models.TextField()),
                ('company_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.ClientCompanies')),
            ],
        ),
        migrations.CreateModel(
            name='PresentationAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.CandidatePresentation')),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
