# Generated by Django 2.2.7 on 2020-01-13 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Clients',
                'verbose_name_plural': 'Clientss',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='statement_of_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internalportal_app.Clients')),
            ],
            options={
                'verbose_name': 'statement_of_work',
                'verbose_name_plural': 'statement_of_works',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internalportal_app.statement_of_work')),
            ],
            options={
                'verbose_name': 'projects',
                'verbose_name_plural': 'projectss',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
