# Generated by Django 2.2.7 on 2020-01-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internalportal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'managed': True, 'verbose_name': 'Clients', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statement_of_work',
            options={},
        ),
        migrations.AlterModelTable(
            name='clients',
            table=None,
        ),
        migrations.AlterModelTable(
            name='projects',
            table=None,
        ),
        migrations.AlterModelTable(
            name='statement_of_work',
            table=None,
        ),
    ]
