# Generated by Django 2.2.7 on 2020-01-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internalportal_app', '0002_auto_20200113_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='avature_steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='statement_of_work',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='statement_of_work',
            name='html',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statement_of_work',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='project_metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_step', models.CharField(max_length=200)),
                ('metric_value', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('sow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internalportal_app.statement_of_work')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internalportal_app.avature_steps')),
            ],
        ),
    ]
