# Generated by Django 2.2.7 on 2020-02-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internalportal_app', '0003_auto_20200126_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_metrics',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statement_of_work',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statement_of_work',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
